/* Auto-generated by genmsg_cpp for file /home/chully/dev/ros/wincube/msg/cmd_msg.msg */
#ifndef WINCUBE_MESSAGE_CMD_MSG_H
#define WINCUBE_MESSAGE_CMD_MSG_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace wincube
{
template <class ContainerAllocator>
struct cmd_msg_ {
  typedef cmd_msg_<ContainerAllocator> Type;

  cmd_msg_()
  : header()
  , left(0)
  , right(0)
  {
  }

  cmd_msg_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , left(0)
  , right(0)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef int8_t _left_type;
  int8_t left;

  typedef int8_t _right_type;
  int8_t right;


  typedef boost::shared_ptr< ::wincube::cmd_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::wincube::cmd_msg_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct cmd_msg
typedef  ::wincube::cmd_msg_<std::allocator<void> > cmd_msg;

typedef boost::shared_ptr< ::wincube::cmd_msg> cmd_msgPtr;
typedef boost::shared_ptr< ::wincube::cmd_msg const> cmd_msgConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::wincube::cmd_msg_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::wincube::cmd_msg_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace wincube

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::wincube::cmd_msg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::wincube::cmd_msg_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::wincube::cmd_msg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "81401375253b01074df288a02d8d49bf";
  }

  static const char* value(const  ::wincube::cmd_msg_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x81401375253b0107ULL;
  static const uint64_t static_value2 = 0x4df288a02d8d49bfULL;
};

template<class ContainerAllocator>
struct DataType< ::wincube::cmd_msg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "wincube/cmd_msg";
  }

  static const char* value(const  ::wincube::cmd_msg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::wincube::cmd_msg_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
int8 left\n\
int8 right\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::wincube::cmd_msg_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::wincube::cmd_msg_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::wincube::cmd_msg_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::wincube::cmd_msg_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.left);
    stream.next(m.right);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct cmd_msg_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::wincube::cmd_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::wincube::cmd_msg_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "left: ";
    Printer<int8_t>::stream(s, indent + "  ", v.left);
    s << indent << "right: ";
    Printer<int8_t>::stream(s, indent + "  ", v.right);
  }
};


} // namespace message_operations
} // namespace ros

#endif // WINCUBE_MESSAGE_CMD_MSG_H

